# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './package/medicine/gui_medicine.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Medicine(object):
    def setupUi(self, Medicine):
        Medicine.setObjectName("Medicine")
        Medicine.resize(222, 30)
        self.gridLayout = QtWidgets.QGridLayout(Medicine)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Medicine)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(15, 15))
        self.label_2.setMaximumSize(QtCore.QSize(15, 15))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/icons/icons8-dot-50.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_remove = QtWidgets.QPushButton(self.frame)
        self.btn_remove.setObjectName("btn_remove")
        self.horizontalLayout.addWidget(self.btn_remove)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Medicine)
        QtCore.QMetaObject.connectSlotsByName(Medicine)

    def retranslateUi(self, Medicine):
        _translate = QtCore.QCoreApplication.translate
        Medicine.setWindowTitle(_translate("Medicine", "Form"))
        self.label.setText(_translate("Medicine", "rakija"))
        self.btn_remove.setText(_translate("Medicine", "Remove"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Medicine = QtWidgets.QWidget()
    ui = Ui_Medicine()
    ui.setupUi(Medicine)
    Medicine.show()
    sys.exit(app.exec_())
