# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './package/graphs/gui_graph_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Graph_widget(object):
    def setupUi(self, Graph_widget):
        Graph_widget.setObjectName("Graph_widget")
        Graph_widget.resize(833, 621)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Graph_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Graph_widget)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.frame_2 = QtWidgets.QFrame(Graph_widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.frame_2)

        self.retranslateUi(Graph_widget)
        QtCore.QMetaObject.connectSlotsByName(Graph_widget)

    def retranslateUi(self, Graph_widget):
        _translate = QtCore.QCoreApplication.translate
        Graph_widget.setWindowTitle(_translate("Graph_widget", "Form"))
        self.label.setText(_translate("Graph_widget", "Legend:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Graph_widget = QtWidgets.QWidget()
    ui = Ui_Graph_widget()
    ui.setupUi(Graph_widget)
    Graph_widget.show()
    sys.exit(app.exec_())
