# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './package/patients/gui_patients.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Patients(object):
    def setupUi(self, Patients):
        Patients.setObjectName("Patients")
        Patients.resize(580, 458)
        self.gridLayout = QtWidgets.QGridLayout(Patients)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Patients)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Patients)
        QtCore.QMetaObject.connectSlotsByName(Patients)

    def retranslateUi(self, Patients):
        _translate = QtCore.QCoreApplication.translate
        Patients.setWindowTitle(_translate("Patients", "Form"))
        self.label.setText(_translate("Patients", "Patiens page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Patients = QtWidgets.QWidget()
    ui = Ui_Patients()
    ui.setupUi(Patients)
    Patients.show()
    sys.exit(app.exec_())
