# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './package/measure/gui_add_medication.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_Medication(object):
    def setupUi(self, Add_Medication):
        Add_Medication.setObjectName("Add_Medication")
        Add_Medication.resize(247, 152)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Add_Medication)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(Add_Medication)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Add_Medication)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.input_medication = QtWidgets.QLineEdit(self.widget_2)
        self.input_medication.setMinimumSize(QtCore.QSize(0, 0))
        self.input_medication.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.input_medication.setObjectName("input_medication")
        self.verticalLayout_2.addWidget(self.input_medication)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(Add_Medication)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_add = QtWidgets.QPushButton(self.widget_3)
        self.btn_add.setAutoDefault(False)
        self.btn_add.setDefault(True)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)
        self.btn_cancle = QtWidgets.QPushButton(self.widget_3)
        self.btn_cancle.setObjectName("btn_cancle")
        self.horizontalLayout.addWidget(self.btn_cancle)
        self.verticalLayout_3.addWidget(self.widget_3)

        self.retranslateUi(Add_Medication)
        QtCore.QMetaObject.connectSlotsByName(Add_Medication)

    def retranslateUi(self, Add_Medication):
        _translate = QtCore.QCoreApplication.translate
        Add_Medication.setWindowTitle(_translate("Add_Medication", "Form"))
        self.label.setText(_translate("Add_Medication", "Enter the name o medications"))
        self.btn_add.setText(_translate("Add_Medication", "Add"))
        self.btn_cancle.setText(_translate("Add_Medication", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Add_Medication = QtWidgets.QWidget()
    ui = Ui_Add_Medication()
    ui.setupUi(Add_Medication)
    Add_Medication.show()
    sys.exit(app.exec_())
