# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './package/measure/gui_measure.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Measure(object):
    def setupUi(self, Measure):
        Measure.setObjectName("Measure")
        Measure.resize(580, 458)
        self.verticalLayout = QtWidgets.QVBoxLayout(Measure)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(Measure)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_start = QtWidgets.QPushButton(self.widget_2)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout.addWidget(self.btn_start)
        spacerItem = QtWidgets.QSpacerItem(379, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_stop = QtWidgets.QPushButton(self.widget_2)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout.addWidget(self.btn_stop)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(Measure)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Measure)
        QtCore.QMetaObject.connectSlotsByName(Measure)

    def retranslateUi(self, Measure):
        _translate = QtCore.QCoreApplication.translate
        Measure.setWindowTitle(_translate("Measure", "Form"))
        self.btn_start.setText(_translate("Measure", "Start"))
        self.btn_stop.setText(_translate("Measure", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Measure = QtWidgets.QWidget()
    ui = Ui_Measure()
    ui.setupUi(Measure)
    Measure.show()
    sys.exit(app.exec_())
